### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by mightyguava** [launchdarkly/go-server-sdk#10]
Most major open source repos support go modules now. Could the LaunchDarkly sdk also add support for it? I think this repo is pretty much set up for it already. Release tags will need a `v` prefix, e.g.`v4.0.0`.

**Comment by eli-darkly** [comment]
It was my impression that go modules are not backward-compatible with code that wasn't previously using them. So if what you mean is "require go modules" rather than "support go modules", I think we would have to be very cautious about such a change; in practice it would probably mean supporting two branches of the SDK for potentially a long time.

**Comment by mightyguava** [comment]
It's not so much that the code isn't compatible, but that the dependency systems aren't compatible. Neither `dep` nor `go mod` require you to write your code in a certain way.

It is possible to provide `go.sum`, and `Gopkg.lock` at the same time with all dependencies in lockstep, but I don't know of any existing tooling for doing so.

Not moving to go modules requires users who are using go modules to have to pin dependencies here and there to upgrade. The inverse may also be true. I don't have much experience with `dep`

**Comment by shawnHartsell** [comment]
@eli-darkly is this issue still being considered? Now that modules are production ready under Go 1.14. It would be nice if this project was converted to modules so it is compatible with the official tool chain.

**Comment by eli-darkly** [comment]
@shawnHartsell We are still looking at it. So far, it's not clear to us whether @mightyguava's comment is correct. There are requirements for Go modules that would not be compatible with `dep` in terms of import paths, at least for a project like this that 1. has subpackages and 2. has a major version number greater than 1.

We are not currently _incompatible_ with the official tool chain, just slightly less convenient to use with it. If we made this change now, we would be more convenient with the official tool chain, but if that made us incompatible with `dep` then that'd be a problem because we still support older versions of Go.

**Comment by shawnHartsell** [comment]
Thanks for the reply @eli-darkly. I'm not an expert with `dep` so I'm not sure if moving to modules would make the project incompatible with dep. However, afaik dep was never an official part of Go so I would consider it to be on the same level as govendor, glide, etc. Fwiw, I haven't encountered an issue where moving a project to modules interfered with one of the older package managers (my team has several projects that use govendor).

Good point about the import paths.  This may or may not work for this project, but one thing I've seen some projects do is tag a new major version (in this case 7) with a go.mod at that version (github.com/launchdarkly/go-server-sdk/v7). That way, folks on V6 (pre modules) stay on the original import path, and folks that want to upgrade to 7 just need to update their import paths. As a library consumer, this would be annoying at first, but makes sense b/c of the major version bump.

I would be curious how other established projects have approached the migration as well.

**Comment by eli-darkly** [comment]
@shawnHartsell 

> afaik dep was never an official part of Go so I would consider it to be on the same level as govendor, glide, etc

And we have not released changes that made the project incompatible with govendor, either. We have an established customer base to keep in mind. Go developers are accustomed to updating language versions since those rarely require code changes, but they went on for a long time without having any usable package manager that was an official tool, and they are not all instantly migrating to modules.

> I would be curious how other established projects have approached the migration as well.

Two examples, each of which has links to further discussion on the subject: 1. [Stripe](https://github.com/stripe/stripe-go#go-module-support) decided to forego module support until some future version. 2. This popular [Elastic](https://github.com/olivere/elastic#releases) client released one major version update that retained `dep` support, and the next major version required modules.

Those are both in effect the same decision with different time frames, and we certainly wouldn't make such a change _without_ a major version bump in any case, so that part can be taken for granted. The only question is which version we would do it in. We have been working on an unrelated major version update for a while, which will have a minimum Go version of 1.13, and depending on timing it might or might not make sense to require module usage at that point.

**Comment by eli-darkly** [comment]
Here's an update to clarify what the sticking point is at the moment, as we understand it.

It is definitely possible to make a project importable by both module code and non-module code— that is, you can put a `go.mod` file in the project which will be used when building with modules, and it will not interfere with anyone who is building without modules— as long as one or both of these things is true:

* The major version is 1.
* The project's canonical import path (which must be used at its import path whenever it is imported, and is also the path that's stored in its `go.mod`) is a `gopkg.in` URL.

There is a third point that I'll get to in a moment, but basically this means that `gopkg.in/launchdarkly/go-server-sdk.v5` could theoretically be OK for both module and non-module use, because `go mod` does _not_ enforce the "import path must have a /v5 suffix if the major version is 5" rule if you use `gopkg.in`; it accepts the `.v5` as an equivalent in that case.

BUT: the third point is that those first two points _must also apply to every transitive dependency_. If any dependency does not meet those same criteria for being able to build in either module or non-module mode _with the same import path_, then you're out of luck.

Unfortunately, we do have such a dependency: [github.com/blang/semver](https://github.com/blang/semver). We are using major version 3 of this package. That version does have a `go.mod` file— and it does _not_ use `gopkg.in`, so the canonical import path as defined in its `go.mod` is `github.com/blang/semver/v3`, and you must use that exact path when you import it if you are building in module mode— but if you're not in module mode, that's an invalid path. Thus, as long as we're importing that package in our code, it's not possible for _our_ package to be equally buildable as a module and a non-module.

It might be that we could switch to a different third-party implementation that doesn't have this issue, but we'll need to take a very close look at how any such thing compares to the one we've been using since we don't want to introduce any unwanted changes to flag evaluation behavior. And I can't guarantee that this is the _only_ dependency that has this issue.

**Comment by eli-darkly** [comment]
Here's an update that I think people will be happy about: the 5.0.0 release of the Go SDK _will_ be a Go module.

The dependency issue mentioned in the previous comment was resolved by removing the problematic third-party dependency; we now use our own semver parsing implementation, which, as a bonus, is much more efficient. All remaining dependencies can be used in either module or non-module mode, and all of the SDK's own packages use `gopkg.in` so their import paths remain the same whether you are using modules or not.

The result is that for people using modules, everything should just work. People who are using `dep`/`govendor`/etc. should also find that it just works. One caution is that since the SDK includes components in several other repositories (such as https://github.com/launchdarkly/go-sdk-common), it is possible that a future update to `go-server-sdk` would require a newer version of `go-sdk-common`, etc., in which case people who have pinned their dependencies with `dep`/`govendor` would need to be sure to update all of the affected packages. But with modules that is not an issue, since `go-server-sdk` will always specify its own preferred dependency versions.

A beta version of this release will be out very soon, which we encourage people to check out and give us feedback on. The GA release should follow within a couple of weeks.

Our current thinking is that the following major version, 6.0.0, will be module-only— meaning that it might stop using `gopkg.in`, and/or might have transitive dependencies that are module-only. We don't have a specific time frame for that; it just seems likely that by the time we get there, everyone will be using modules.

**Comment by eli-darkly** [comment]
OK, [v5.0.0-beta.1](https://github.com/launchdarkly/go-server-sdk/releases/tag/v5.0.0-beta.1) is out now, for anyone who would like an early look.

**Comment by eli-darkly** [comment]
And the [5.0.0 GA release](https://github.com/launchdarkly/go-server-sdk/releases/tag/5.0.0) is now out as well. Thanks for everyone's patience with this process.
