### ISSUE TITLE
Unable to use ldvalue(go-sdk-common.v1) in my program with go-server-sdk.v4

### ISSUE THREAD

**Issue by gillmk** [launchdarkly/go-server-sdk#24]
**Is this a support request?**
No

**Describe the bug**
Build failure while using go-sdk-common.v1/ldvalue 

**To reproduce**
Steps to reproduce the behavior.
-  go get gopkg.in/launchdarkly/go-server-sdk.v4
  go get gopkg.in/launchdarkly/go-sdk-common.v1

- Source code 
```
package main

import (
        "fmt"
        "time"
        ld "gopkg.in/launchdarkly/go-server-sdk.v4"
        "gopkg.in/launchdarkly/go-server-sdk.v4/ldlog"
        "gopkg.in/launchdarkly/go-sdk-common.v1/ldvalue"
)

const (
   sdk_key = "blah"
   feature = "test-feature"
)

func main() {
        config := ld.DefaultConfig
        config.Loggers.SetMinLevel(ldlog.Debug)
        client, _ := ld.MakeCustomClient(sdk_key, config, 5*time.Second)
         account := [3]string{"acc1", "acc2", "acc3"}

       for {

        for _, acc := range(account) {
           go func(a string) {
           user := ld.NewUserBuilder(a).
              Custom("region", ldvalue.String("us-south")).Build()
           showFeature, _ := client.BoolVariation(feature, user, false)
           if showFeature {
               fmt.Println("Showing your feature to " + *user.Key)
           } else {
                // the code to run if the feature is off
                fmt.Println("Not showing your feature to " + *user.Key)
           }
           time.Sleep(10 * time.Millisecond)
         }(acc)
        }
        time.Sleep(1 * time.Second)
        fmt.Println("*****************************************")
        }
        client.Close()
}

```
- go build ./main.go
**Expected behavior**
No compile error 

**Logs**
 go run ./main.go 

```
# command-line-arguments
./main.go:27:46: cannot use "gopkg.in/launchdarkly/go-sdk-common.v1/ldvalue".String("us-south") (type "gopkg.in/launchdarkly/go-sdk-common.v1/ldvalue".Value) as type "gopkg.in/launchdarkly/go-server-sdk.v4/vendor/gopkg.in/launchdarkly/go-sdk-common.v1/ldvalue".Value in argument to ldclient.NewUserBuilder(a).Custom
```

I can solve this problem by removing from vendor folder  launchdarkly/go-server-sdk.v4/vendor/gopkg.in/launchdarkly/go-sdk-common.v1/ . But this is hacky. Any other way to fix this problem?

**SDK version**
go-server-sdk.v4

**Language version, developer tools**
go version go1.13.4 darwin/amd64

**OS/platform**
Mac

**Additional context**

**Comment by eli-darkly** [comment]
I'm a little confused as to why you're using `go get` in Go 1.13, and whether it is loading these packages into your GOPATH or your module cache. This is a use case we're not familiar with. From what I remember, I would normally expect `go get` to recursively load transitive dependencies and to _not_ pull in files from `vendor/`, but we have not used `go get` in a long time.

**Comment by eli-darkly** [comment]
I heard from one of our solutions engineers that some of your projects use modules while others use dep, or other approaches to dependency management, but which one are you trying to use in this case?

**Comment by eli-darkly** [comment]
Assuming you are _not_ using modules, I would expect the behavior of `go get gopkg.in/launchdarkly/go-server-sdk.v4` to be 1. it should load `gopkg.in/launchdarkly/go-server-sdk.v4` into `$GOPATH/src`, 2. it should also load all of that package's transitive dependencies, such as `gopkg.in/launchdarkly/go-sdk-common.v1`, into `$GOPATH/src`, and it should _not_ load the `vendor/` tree for any of those. That is what the `go get` (non-module version) documentation says, and it's what would make sense since the tool would not be very useful if you had to load every transitive dependency yourself and if the common use of `vendor/` would confuse it so badly. It should not be particularly unusual for one package to have a transitive dependency on another package, mention its types in an exported method, and vendor it.

But there must be something I'm missing, because when I tried it myself (both in a pre-Go-1.11 version, and in a recent version but from inside my `GOPATH` and with `GO111MODULE=off`) it behaved just like you said: it did _not_ follow the transitive dependencies, and it _did_ load `vendor/`. So I'm pretty confused. Again, I may be way off base because our practice has been to use `dep` for projects that cannot yet be migrated to modules, so I haven't relied on `go get` in a while.

**Comment by eli-darkly** [comment]
Again assuming that using modules is not an option for you in this project... I've verified that, as I thought, both `govendor` and `dep` behave the way that I expected `go get` would behave: that is, they do _not_ pull in the `vendor/` tree, and they _do_ load transitive dependencies recursively so that simply fetching `gopkg.in/launchdarkly/go-server-sdk.v4` will give you `go-sdk-common.v1` and everything else that the SDK needs, at the top level of your own `vendor/` tree, which should prevent the kind of build error you're seeing.

**Comment by gillmk** [comment]
Thanks @eli-darkly for your response. Yes, moving to modules needs some effort by many teams, I'm trying to find a way with least effort.

**Comment by eli-darkly** [comment]
Well, if `dep` is an option, I would recommend giving that a try since it also has the advantage of letting you pin dependencies, which `go get` can't do.

**Comment by eli-darkly** [comment]
@gillmk I hope this was resolved for you. I'm closing this issue now since we haven't heard anything further, but please feel free to reopen it if there's still a problem.
